### ISSUE TITLE
(macOS) Handle audio samples in SCStreamOutput

### ISSUE THREAD

**Issue by clearlysid** [CapSoftware/scap#10]
Currently, only video samples are being processed. Study and implemented the process to handle audio as well.

**Comment by clearlysid** [comment]
This will likely first have to be handled upstream in `screencapturekit-rs`, maybe I can look into creating a PR for it.

**Comment by anubhavitis** [comment]
@clearlysid maybe I can help you to create PR for `screencapturekit-rs` for handling the audio samples in SCStreamOutput. I am interested.

**Comment by clearlysid** [comment]
Yup, go for it! I'm sure @1313 will appreciate a PR 🙌

**Comment by clearlysid** [comment]
Closing this issue for now, since I'm of the opinion we should handle audio for cypher via cross-platform Rust solutions instead of ScreenCaptureKit, but we might revise this decision in the future.
