### ISSUE TITLE
With this library, can I get the audio stream of the microphone or system sound separately?

### ISSUE THREAD

**Issue by daidi** [CapSoftware/scap#32]
Thanks to the author for contributing this library, I have a question that could be foolish...

With this library, can I get the audio stream of the microphone or system sound separately?

**Comment by clearlysid** [comment]
Sorry about the delay is getting back. Yes, you can get the audio stream and system sound separately with our libraries! Work on this is however, still under progress in the `v0.0.1/main` branch of this repo. We expect to be able to finish this within this month.

**Comment by daidi** [comment]
No problem at all, thanks for getting back to me. It's great to hear that your libraries can separate the audio stream and system sound. I'm looking forward to the completion of this work in the v0.0.1/main branch. Please keep me updated on the progress. Thanks in advance.

**Comment by clearlysid** [comment]
Planned as part of a v2 for `acap` crate.

**Comment by louis030195** [comment]
@clearlysid 
any news on this? struggling to find how to extract audio  in the main.rs
also had to tweak main.rs to record display, who use visual studio code in 2024? :D all the way cursor.com
