### ISSUE TITLE
failed to run custom build command for `apple-sys v0.2.0`

### ISSUE THREAD

**Issue by daidi** [CapSoftware/scap#48]
error: failed to run custom build command for `apple-sys v0.2.0`

Caused by:
  process didn't exit successfully: `/Users/dorothy/IdeaProjects/scap-test/target/debug/build/apple-sys-72797455d4c0f3e0/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=macos.inc.rs
  cargo:rerun-if-changed=ios.inc.rs
  cargo:rustc-link-lib=framework=CoreMedia

  --- stderr
  thread 'main' panicked at /Users/dorothy/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/bindgen-0.63.0/ir/context.rs:1971:26:
  Non floating-type complex? Type(_Complex _Float16, kind: Complex, cconv: 100, decl: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None), canon: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None)), Type(_Float16, kind: Float16, cconv: 100, decl: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None), canon: Cursor( kind: NoDeclFound, loc: builtin definitions, usr: None))
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by clearlysid** [comment]
This likely happens due to a mismatch in xcode build tools and rust compiler. Can you update/reinstall to the latest version fo Xcode build tools on your macOS and retry?

**Comment by clearlysid** [comment]
Marking this as closed since my recommended solution worked for a friend who ran into the same error. Please feel free to reopen if more help is needed, thanks!

**Comment by huywang** [comment]
I have also encountered this problem, and currently, Xcode is the latest version. How to solve it? Should we reinstall Xcode?

**Comment by clearlysid** [comment]
@huywang can you share your Mac specifications here? What OS, model and CPU is it?

**Comment by clearlysid** [comment]
On closer inspection, I think this bug affects `apple-sys` on Intel-based Macs. We need to figure out a solution to get `scap` (and everything it powers) running on Intel machines soon.

**Comment by huywang** [comment]
> @huywang can you share your Mac specifications here? What OS, model and CPU is it?

CPU: 2.6 GHz 6 cores Intel Core i7
MacOS： 14.4.1 (23E224)

**Comment by clearlysid** [comment]
@huywang @daidi our latest `main` branch should solve for this, but we don't have an Intel Mac on our end to confirm. Can one of you let us know if this works?

**Comment by huywang** [comment]
> @huywang @daidi our latest `main` branch should solve for this, but we don't have an Intel Mac on our end to confirm. Can one of you let us know if this works?

Thanks for your quickly reply, but this issue always exist.
![image](https://github.com/helmerapp/scap/assets/3851578/20ef182c-1467-4a44-9f61-cedfe15dbb86)

**Comment by clearlysid** [comment]
@huywang can you run `cargo clean` in your project and delete Cargo.lock file and try once?

**Comment by huywang** [comment]
> @huywang can you run `cargo clean` in your project and delete Cargo.lock file and try once?
<img width="815" alt="image" src="https://github.com/helmerapp/scap/assets/3851578/26daebae-1708-4903-9076-3d3828e78a81">

<img width="1790" alt="image" src="https://github.com/helmerapp/scap/assets/3851578/d15f6893-1639-48c5-a53a-e1e760146dcf">

**Comment by huywang** [comment]
> @huywang can you run `cargo clean` in your project and delete Cargo.lock file and try once?
After use newest github dependency, this issue disappeared. thanks. Could you update to the cargo registry?

**Comment by clearlysid** [comment]
Yes, will do within the next couple of days. Glad our fix worked!
