### ISSUE TITLE
(Windows) Run capture engine on a different / non-blocking thread.

### ISSUE THREAD

**Issue by clearlysid** [CapSoftware/scap#5]
Currently, the capturing "hijacks" the main thread and we lose external control on it. Ideally, I would like the capturing to be async/non-blocking in nature. I don't yet know the best approach to do this. ScreenCaptureKit on macOS is non-blocking and works closer to how I want it to work but I don't know how it achieves that under the hood.

Open questions:
1. Should the capturer simply be run on an independent thread?
2. Should this be implemented upstream in `windows-capture` or should it be handled in `cypher` itself?

**Comment by NiiightmareXD** [comment]
Added To [windows-capture v1.0.22](https://github.com/NiiightmareXD/windows-capture)

Instead of WindowsCaptureHandler::start use WindowsCaptureHandler::start_free_threaded

**Comment by clearlysid** [comment]
Thanks a ton! Sending you a message on Discord and handling this in #15 🥳
