### ISSUE TITLE
Usage example is outdated

### ISSUE THREAD

**Issue by thewh1teagle** [CapSoftware/scap#50]
The usage example in readme.md is outdated and it doesn't work when copy pasting.

**Comment by Pranav2612000** [comment]
Thank you for pointing it out @thewh1teagle . We'll update the example ASAP.

**Comment by clearlysid** [comment]
Fixed with latest commit: https://github.com/helmerapp/scap/commit/a33cf695768178b2649c4dff3d4a1a014ccb82fb
