### ISSUE TITLE
(Linux) Create mechanism to capture frames

### ISSUE THREAD

**Issue by clearlysid** [CapSoftware/scap#6]
I would love to support Linux and make scap fully cross-platform, but don't have a linux machine to be able to do this. Any help / contributions in this regard are welcome!

**Comment by MAlba124** [comment]
What is the status on this? I'm interested in contributing.

**Comment by clearlysid** [comment]
Hey @MAlba124, thanks for your interest! We are close to wrapping up the `v0.0.1` for Win/Mac, and could surely use a hand with Linux. I recommend using the [v0.0.1/main](https://github.com/clearlysid/scap/tree/v0.0.1/main) branch as your base and see if you can extend the `engine` module to support Linux, either using FFmpeg or a different means.

Let us know if you like to take this up and I'll assign it to you — you can also join our [Discord](https://discord.gg/hfgnGE8F) and ask me or @Pranav2612000 for help in the `scap` channel 🙌

**Comment by MAlba124** [comment]
Okay, sounds good! I'm all up for it.

**Comment by clearlysid** [comment]
Well then, welcome onboard! Reach out in the Discord `scap` channel if you need a hand. Looking forward to your PR 🤝

**Comment by clearlysid** [comment]
Closed with #27
