### ISSUE TITLE
Rename CGPoint and CGSize 

### ISSUE THREAD

**Issue by Pranav2612000** [CapSoftware/scap#60]
CGPoint and CGSize are macOS propriety API names. It would be better to rename the structs to something more generic
for e.g "Point" and "Size" respectively.
Users would be able to access the structs using "scap::Point { .. }" and "scap::Size { .. }"

**Comment by MAlba124** [comment]
I guess `CGRect` should also be renamed.

**Comment by clearlysid** [comment]
Taking this one up, I could use a small win for the day 😅
