### ISSUE TITLE
Encode frames to video using FFmpeg / OS built-in encoders

### ISSUE THREAD

**Issue by clearlysid** [CapSoftware/scap#8]
We're able to capture frames on Windows very well. Now to encode them into video files.

As of now, I think we only really need to provide `h264` and `hevc` codecs where suitable. All other codecs can be added later as and when requested or needed.

**Comment by NiiightmareXD** [comment]
Should we use [video-rs](https://github.com/oddity-ai/video-rs)? is uses FFmpeg and h264

**Comment by NiiightmareXD** [comment]
Or maybe even [OpenCV](https://docs.rs/opencv/latest/opencv/videoio/struct.VideoWriter.html)

**Comment by clearlysid** [comment]
`video-rs` wraps [ffmpeg-next](https://github.com/zmwangx/rust-ffmpeg). Actually, I would prefer to use [Remotion's fork](https://github.com/remotion-dev/rust-ffmpeg) which actually strips all the unnecessary codecs and extra stuff from the FFmpeg binaries and cuts the size from 80Mbs to just 4-5Mb if I recall correctly.

**Comment by clearlysid** [comment]
It looks like we can use Window's Media Foundation encoders [directly via FFmpeg](https://ffmpeg.org/ffmpeg-codecs.html) itself (Check 9.19 MediaFoundation), which would be pretty neat 🥳

**Comment by NiiightmareXD** [comment]
Great I think we can use FFmpeg for now and benchmark its performance and if it was too slow we can switch to OBS method.

Should we implement this in cypher or screencapturekit-rs and windows-capture?

**Comment by clearlysid** [comment]
We should implement FFmpeg in cypher.

For `screencapture-rs`, it is likely out of scope since it is only meant for bindings to [Apple's API](https://developer.apple.com/documentation/screencapturekit?language=objc)).

For `windows-capture`, it's your call. My thought is to keep it focused for Windows and use the OS built-in encoder there. If the FFmpeg route doesn't work out in Cypher, we'll use the built-in one from windows-capture instead.

**Comment by clearlysid** [comment]
@anubhavitis would you like to give this a shot or should I pick it up?

**Comment by clearlysid** [comment]
Track progress in #18 ✅

**Comment by clearlysid** [comment]
Closing this issue as macOS is taken care of by @Pranav2612000 and Windows encoding will be tackled natively soon in `windows-capture` thanks to @NiiightmareXD 🥳
